import { BorderStyle, BorderConfig, AsciiBordersSettings } from "./utils/types";

export const DEFAULT_BORDER_STYLES: Record<string, BorderStyle> = {
	heart: {
		top: "══ஓ๑♡๑ஓ══",
		bottom: "══ஓ๑♡๑ஓ══",
		left: "║",
		right: "║",
		topLeft: "╔",
		topRight: "╗",
		bottomLeft: "╚",
		bottomRight: "╝",
	},
	star: {
		top: "══✧･ﾟ: *✧･ﾟ:*══",
		bottom: "══✧･ﾟ: *✧･ﾟ:*══",
		left: "║",
		right: "║",
		topLeft: "╔",
		topRight: "╗",
		bottomLeft: "╚",
		bottomRight: "╝",
	},
	simple: {
		top: "═══════════",
		bottom: "═══════════",
		left: "║",
		right: "║",
		topLeft: "╔",
		topRight: "╗",
		bottomLeft: "╚",
		bottomRight: "╝",
	},
	double: {
		top: "═",
		bottom: "═",
		left: "║",
		right: "║",
		topLeft: "╔",
		topRight: "╗",
		bottomLeft: "╚",
		bottomRight: "╝",
	},
	single: {
		top: "─",
		bottom: "─",
		left: "│",
		right: "│",
		topLeft: "┌",
		topRight: "┐",
		bottomLeft: "└",
		bottomRight: "┘",
	},
	rounded: {
		top: "─",
		bottom: "─",
		left: "│",
		right: "│",
		topLeft: "╭",
		topRight: "╮",
		bottomLeft: "╰",
		bottomRight: "╯",
	},
};

export const DEFAULT_SETTINGS: AsciiBordersSettings = {
	borders: {
		heart: { style: DEFAULT_BORDER_STYLES.heart, centerText: false },
		star: { style: DEFAULT_BORDER_STYLES.star, centerText: false },
		simple: { style: DEFAULT_BORDER_STYLES.simple, centerText: false },
		double: { style: DEFAULT_BORDER_STYLES.double, centerText: false },
		single: { style: DEFAULT_BORDER_STYLES.single, centerText: false },
		rounded: { style: DEFAULT_BORDER_STYLES.rounded, centerText: false },
	},
};
